export const MENU = {
  APERITIVOS: [
    {
      id: 1,
      url: '',
      title: 'Brochetas de langostino y calabacín',
      price: 'Q. 30',
      desc: 'Ricas brochetas de langostino y calabacín bañadas en salsa.',
    },
    {
      id: 2,
      url: '#',
      title: 'Tostadas con sardinillas',
      price: 'Q. 20',
      desc: 'Tostadias recien hechas con sardinillas de importación.',
    },
    {
      id: 3,
      url: '#',
      title: 'Montaditos de pincho moruno',
      price: 'Q. 25',
      desc: 'Moruno cocido a con pan italiano con atún.',
    },
  ],
  PRINCIPALES: [
    {
      id: 1,
      url: '#',
      title: 'Salmón a la plancha con arroz y espárragos',
      price: 'Q. 50',
      desc: 'Ricon salmón importado desde la costa oeste a la plancha con arroz y espárragos frescos.',
    },
    {
      id: 2,
      url: '#',
      title: 'Ternera guisada con setas',
      price: 'Q. 45',
      desc: 'Ternera guisada con termino al gusto y setas del oriente.',
    },
    {
      id: 2,
      url: '#',
      title: 'Ternera guisada con setas',
      price: 'Q. 45',
      desc: 'Ternera guisada con termino al gusto y setas del oriente.',
    },
    {
      id: 3,
      url: '#',
      title: 'Costilla de cerdo con vino tinto',
      price: 'Q. 65',
      desc: 'Costilla de cerdo bañada con salsa de vino tinto nacional.',
    },
    {
      id: 4,
      url: '#',
      title: 'Salmón con trigueros y jusías blancas',
      price: 'Q. 55',
      desc: 'Salmón de trigueros de 20 cm. acompñada de jusías blancas.',
    },
    {
      id: 5,
      url: '#',
      title: 'Tacos de carne a la cerveza',
      price: 'Q. 50',
      desc: 'Tacos tostados en aceite con carne de ternera y salsa de cerveza.',
    },
    {
      id: 6,
      url: '#',
      title: 'Pasta con salmón a la mostaza',
      price: 'Q. 40',
      desc: 'Pasta acompñada de salmón bañada con mostaza.',
    },
    {
      id: 7,
      url: '#',
      title: 'Robin stick con papas',
      price: 'Q. 35',
      desc: 'Hamburguesa con carne, tocino acompañado de papas fritas.',
    },
    {
      id: 8,
      url: '#',
      title: 'Hamburguesa vegana de alubia roja y quinoa',
      price: 'Q. 45',
      desc: 'Hamburguesa vegana baja en grasa con salsa de alubia roja y quinoa.',
    },
    {
      id: 9,
      url: '#',
      title: 'Lasaña de lenguado',
      price: 'Q. 40',
      desc: 'Lasaña de tres capas rellena de lenguado recien hecho.',
    },
    {
      id: 10,
      url: '#',
      title: 'Pierna de cordero al horno',
      price: 'Q. 40',
      desc: 'Pierna de cordero al horno bañada con salsa.',
    },
    {
      id: 11,
      url: '#',
      title: 'Albóndigas veganas con salsa de tomate',
      price: 'Q. 40',
      desc: 'Albóndigas veganas recien hechas acompñadas de salsa de tomate fresca.',
    },
  ],
  ENSALADAS: [
    {
      id: 1,
      url: '#',
      title: 'Ensalada caesar',
      price: 'Q. 32',
      desc: 'Ensalada caesar con verduras frescas acompañado de un filete de pollo.',
    },
    {
      id: 2,
      url: '#',
      title: 'Ensalada con camarones',
      price: 'Q. 35',
      desc: 'Ensalada caesar con verduras frescas acompañado de pequeños camarones de importación.',
    },
    {
      id: 3,
      url: '#',
      title: 'Ensalada de pollo',
      price: 'Q. 28',
      desc: 'Ensalada de pollo con acompañada de diferentes verduras frescas.',
    },
    {
      id: 4,
      url: '#',
      title: 'Ensalada verde con arroz',
      price: 'Q. 28',
      desc: 'Ensalada con verduras verdes con arroz a la valenciana.',
    },
  ],
  BEBIDAS: [
    {
      id: 1,
      url: '#',
      title: 'Pichel de limonada natural',
      price: 'Q. 35',
      desc: 'Pichel de limonada natural para compartir con toda la familia o solo con amigos.',
    },
    {
      id: 2,
      url: '#',
      title: 'Pichel de naranja natural',
      price: 'Q. 30',
      desc: 'Pichel de naranja natural para compartir con toda la familia o solo con amigos.',
    },
    {
      id: 3,
      url: '#',
      title: 'Bebida gaseosa',
      price: 'Q. 12',
      desc: 'Gaseosa de diferentes sabores para acompañar su comida.',
    },
    {
      id: 4,
      url: '#',
      title: 'Cerveza Gallo',
      price: 'Q. 20',
      desc: 'Cerveza Gallo nacional.',
    },
    {
      id: 5,
      url: '#',
      title: 'Cerveza Corona',
      price: 'Q. 20',
      desc: 'Cerveza Corona nacional.',
    },
  ],
  POSTRES: [
    {
      id: 1,
      url: '#',
      title: 'Malteada de fresa',
      price: 'Q. 15',
      desc: 'Malteada de fresa natural, puede agregarle leche si así lo desea.',
    },
    {
      id: 2,
      url: '#',
      title: 'Licuado de banano',
      price: 'Q. 15',
      desc: 'Licuado de banano natural, puede agregarle leche si así lo desea.',
    },
    {
      id: 3,
      url: '#',
      title: 'Pastel de 4 capas',
      price: 'Q. 100',
      desc: 'Llévate este pastel de 4 capas con sabor a naranja natural para tus fiestas y compartir con toda la familia',
    },
    {
      id: 4,
      url: '#',
      title: 'Pie de queso',
      price: 'Q. 15',
      desc: 'Rebanada de pie de queso frio.',
    },
  ],
};
